language: generic

sudo: required

dist: trusty

services:
  - docker
  
install:
  - docker pull lamtev/latex

matrix:
  include:
    - env: LAB="lab1"
    - env: LAB="lab2"
    - env: LAB="lab3"

script:
  - docker run -v $TRAVIS_BUILD_DIR:/electroch_labs lamtev/latex /bin/bash -c " cd electroch_labs/${LAB} && pdflatex ${LAB}.tex && pdflatex ${LAB}.tex "
  - sudo chmod 777 ${TRAVIS_BUILD_DIR}/${LAB}/${LAB}.pdf
  
deploy:
  provider: releases
  api_key: "$GITHUB_DEPLOY_TOKEN"
  file: 
    - ${TRAVIS_BUILD_DIR}/${LAB}/${LAB}.tex
  skip_cleanup: true
  on:
    tags: true
