language: generic

sudo: required

dist: trusty

services:
  - docker
  
install:
  - docker pull lamtev/latex:full

matrix:
  include:
    - env: LAB="lab1"
    - env: LAB="lab2"
    - env: LAB="lab3"
    - env: LAB="lab11a"
    - env: LAB="lab5"
    - env: LAB="lab4"
    - env: LAB="lab6"
    - env: LAB="lab7"
    - env: LAB="lab8"
    - env: LAB="lab10"

script:
  - docker run -v $TRAVIS_BUILD_DIR:/electroch_labs lamtev/latex:full /bin/bash -c " cd electroch_labs/${LAB} && pdflatex ${LAB}.tex && pdflatex ${LAB}.tex "
  - sudo chmod 777 ${TRAVIS_BUILD_DIR}/${LAB}/${LAB}.pdf
  
deploy:
  provider: releases
  api_key: "$GITHUB_DEPLOY_TOKEN"
  file: 
    - ${TRAVIS_BUILD_DIR}/${LAB}/${LAB}.pdf
  skip_cleanup: true
  on:
    tags: true
